# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-09 13:49
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='modbusDataTable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetimestamp', models.DateTimeField(unique=True)),
                ('machineData', django.contrib.postgres.fields.jsonb.JSONField()),
                ('humanData', django.contrib.postgres.fields.jsonb.JSONField(null=True)),
            ],
        ),
    ]
