# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-07 13:23
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('option1', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='modbusData',
            new_name='humanReadableDataTable',
        ),
        migrations.RenameModel(
            old_name='humanReadableData',
            new_name='modbusDataTable',
        ),
    ]
