# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-08 11:22
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('option1', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='humanreadabledatatable',
            name='datetimestamp',
            field=models.DateTimeField(default=datetime.datetime(2017, 3, 8, 11, 22, 1, 82008), unique=True),
            preserve_default=False,
        ),
    ]
